### ISSUE TITLE
missing data points

### ISSUE THREAD

**Issue by brembs** [brembslab/Optomotorics-Bachelor-Thesis#2]
About ~500 data points are missing at the end of the raw data

**Comment by Eanders1** [comment]
I have ran a bunch of tests now and concluded a few things:
- The number of missing data points seem to be less than 50 and not 500. 
- Irrespective of the period duration or the entire experiment, it always seems to be about 40±2 missing data points. 
- As the number of missing data points is so consistent but with still some variation, my guess is that it is a computational problem and not a problem with the code itself. The solution is of course within the code.

**Comment by brembs** [comment]
Anders fixed it.
